# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
POST http://127.0.0.1:8085/api/create-tenant/
Content-Type: application/json

{
    "name": "example_tenant",
    "config_settings": {"key1": "value1", "key2": "value2"}
}

###
POST http://127.0.0.1:8085/api/ask
Content-Type: application/json

{
    "question": "What is the weather today?"
}
